//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITourist.App_Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITourist.App_Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to the route.
        /// </summary>
        public static string AddPlaceToTheRoute {
            get {
                return ResourceManager.GetString("AddPlaceToTheRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add region.
        /// </summary>
        public static string AddRegion {
            get {
                return ResourceManager.GetString("AddRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to bookmarks.
        /// </summary>
        public static string AddToBookmarks {
            get {
                return ResourceManager.GetString("AddToBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All photos.
        /// </summary>
        public static string AllPhotos {
            get {
                return ResourceManager.GetString("AllPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved.
        /// </summary>
        public static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average  time of passing:.
        /// </summary>
        public static string AveragePassTime {
            get {
                return ResourceManager.GetString("AveragePassTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks.
        /// </summary>
        public static string Bookmarks {
            get {
                return ResourceManager.GetString("Bookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chechpoint added successfully.
        /// </summary>
        public static string CheckPointAdded {
            get {
                return ResourceManager.GetString("CheckPointAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Such checkpoint doesn&apos;t exists.
        /// </summary>
        public static string CheckPointNotExists {
            get {
                return ResourceManager.GetString("CheckPointNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose сountry.
        /// </summary>
        public static string ChooseCountry {
            get {
                return ResourceManager.GetString("ChooseCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose region.
        /// </summary>
        public static string ChooseRegion {
            get {
                return ResourceManager.GetString("ChooseRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose type:.
        /// </summary>
        public static string ChooseType {
            get {
                return ResourceManager.GetString("ChooseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chosen places.
        /// </summary>
        public static string ChosenPlaces {
            get {
                return ResourceManager.GetString("ChosenPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City/region.
        /// </summary>
        public static string CityOrRegion {
            get {
                return ResourceManager.GetString("CityOrRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment cannot be empty.
        /// </summary>
        public static string CommentEmpty {
            get {
                return ResourceManager.GetString("CommentEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm registration.
        /// </summary>
        public static string ConfirmRegistration {
            get {
                return ResourceManager.GetString("ConfirmRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm route.
        /// </summary>
        public static string ConfirmRoute {
            get {
                return ResourceManager.GetString("ConfirmRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control panel.
        /// </summary>
        public static string ControlPanel {
            get {
                return ResourceManager.GetString("ControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries do not matched.
        /// </summary>
        public static string CountriesNotMatched {
            get {
                return ResourceManager.GetString("CountriesNotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Such country doesn&apos;t exist.
        /// </summary>
        public static string CountryNotExists {
            get {
                return ResourceManager.GetString("CountryNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create route.
        /// </summary>
        public static string CreateRoute {
            get {
                return ResourceManager.GetString("CreateRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create route.
        /// </summary>
        public static string CreateYourRoute {
            get {
                return ResourceManager.GetString("CreateYourRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My route.
        /// </summary>
        public static string DefaultRouteName {
            get {
                return ResourceManager.GetString("DefaultRouteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dmitriy Bekuzarov.
        /// </summary>
        public static string Dima {
            get {
                return ResourceManager.GetString("Dima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not save.
        /// </summary>
        public static string DoNotSave {
            get {
                return ResourceManager.GetString("DoNotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to &apos;My routes&apos;?.
        /// </summary>
        public static string DoYouWantToSaveRoute {
            get {
                return ResourceManager.GetString("DoYouWantToSaveRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration passed  successfully. To confirm registration visit your mail!.
        /// </summary>
        public static string EmailConfirmation {
            get {
                return ResourceManager.GetString("EmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter translations.
        /// </summary>
        public static string EnterRouteTranslations {
            get {
                return ResourceManager.GetString("EnterRouteTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name of the route.
        /// </summary>
        public static string EnterTheNameOfTheRoute {
            get {
                return ResourceManager.GetString("EnterTheNameOfTheRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        public static string Experience {
            get {
                return ResourceManager.GetString("Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended search.
        /// </summary>
        public static string ExtendedSearch {
            get {
                return ResourceManager.GetString("ExtendedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to five star of five.
        /// </summary>
        public static string FiveStarOfFive {
            get {
                return ResourceManager.GetString("FiveStarOfFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to four star of five.
        /// </summary>
        public static string FourStarOfFive {
            get {
                return ResourceManager.GetString("FourStarOfFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to bookmarks.
        /// </summary>
        public static string GoToBookmarks {
            get {
                return ResourceManager.GetString("GoToBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid country ID.
        /// </summary>
        public static string InvalidCountryID {
            get {
                return ResourceManager.GetString("InvalidCountryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email. User with this email already exists.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid place ID value.
        /// </summary>
        public static string InvalidPlaceID {
            get {
                return ResourceManager.GetString("InvalidPlaceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token.
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «iTourist» is a very convenient, powerful service designed for tourists. This is a useful guide when you are traveling to a foreign country. You can browse popular places, create routes or choose existing ones. You can also share your routes with other tourists. Travel, gain experience and become the most adventurous person in the world!.
        /// </summary>
        public static string ITouristDescription {
            get {
                return ResourceManager.GetString("ITouristDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konstantin Chikerenda.
        /// </summary>
        public static string Kostya {
            get {
                return ResourceManager.GetString("Kostya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave a comment.
        /// </summary>
        public static string LeaveComment {
            get {
                return ResourceManager.GetString("LeaveComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alexey Spodarets.
        /// </summary>
        public static string Lesha {
            get {
                return ResourceManager.GetString("Lesha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like.
        /// </summary>
        public static string Like {
            get {
                return ResourceManager.GetString("Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likes.
        /// </summary>
        public static string Likes {
            get {
                return ResourceManager.GetString("Likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in with:.
        /// </summary>
        public static string LogInWith {
            get {
                return ResourceManager.GetString("LogInWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish route at the start place.
        /// </summary>
        public static string LoopRoute {
            get {
                return ResourceManager.GetString("LoopRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make public.
        /// </summary>
        public static string MakePublic {
            get {
                return ResourceManager.GetString("MakePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maria Voytenko.
        /// </summary>
        public static string Masha {
            get {
                return ResourceManager.GetString("Masha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maxim Erokhin.
        /// </summary>
        public static string Maxim {
            get {
                return ResourceManager.GetString("Maxim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iTourist for mobile.
        /// </summary>
        public static string MobileApps {
            get {
                return ResourceManager.GetString("MobileApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name in English.
        /// </summary>
        public static string NameEn {
            get {
                return ResourceManager.GetString("NameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name in Russian.
        /// </summary>
        public static string NameRu {
            get {
                return ResourceManager.GetString("NameRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name should contain: .
        /// </summary>
        public static string NameShouldContain {
            get {
                return ResourceManager.GetString("NameShouldContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No places.
        /// </summary>
        public static string NoPlaces {
            get {
                return ResourceManager.GetString("NoPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no regions in this country.
        /// </summary>
        public static string NoRegions {
            get {
                return ResourceManager.GetString("NoRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No routes.
        /// </summary>
        public static string NoRoutes {
            get {
                return ResourceManager.GetString("NoRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we have not found such user with such email. Try again.
        /// </summary>
        public static string NoSuchEmail {
            get {
                return ResourceManager.GetString("NoSuchEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all fields are filled.
        /// </summary>
        public static string NotAllFieldsAreFilled {
            get {
                return ResourceManager.GetString("NotAllFieldsAreFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing found on request &quot;{0}&quot;.
        /// </summary>
        public static string NothingFound {
            get {
                return ResourceManager.GetString("NothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one star of five.
        /// </summary>
        public static string OneStarOfFive {
            get {
                return ResourceManager.GetString("OneStarOfFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimize waypoints.
        /// </summary>
        public static string OptimizeWaypoints {
            get {
                return ResourceManager.GetString("OptimizeWaypoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or choose existing one.
        /// </summary>
        public static string OrChooseExisting {
            get {
                return ResourceManager.GetString("OrChooseExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order by: .
        /// </summary>
        public static string OrderBy {
            get {
                return ResourceManager.GetString("OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our team.
        /// </summary>
        public static string OurTeam {
            get {
                return ResourceManager.GetString("OurTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404, Page not found.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PassWord {
            get {
                return ResourceManager.GetString("PassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string PasswordsAreNotEqual {
            get {
                return ResourceManager.GetString("PasswordsAreNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place is already in the route.
        /// </summary>
        public static string PlaceIsAlreadyInTheRoute {
            get {
                return ResourceManager.GetString("PlaceIsAlreadyInTheRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plase does not exist.
        /// </summary>
        public static string PlaceNotExist {
            get {
                return ResourceManager.GetString("PlaceNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place was removed successfully.
        /// </summary>
        public static string PlaceRemovedSuccessfully {
            get {
                return ResourceManager.GetString("PlaceRemovedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Places.
        /// </summary>
        public static string Places {
            get {
                return ResourceManager.GetString("Places", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place was successfully added to the route.
        /// </summary>
        public static string PlaceWasAddedToTheRoute {
            get {
                return ResourceManager.GetString("PlaceWasAddedToTheRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular places.
        /// </summary>
        public static string PopularPlaces {
            get {
                return ResourceManager.GetString("PopularPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview route.
        /// </summary>
        public static string PreviewRoute {
            get {
                return ResourceManager.GetString("PreviewRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recomended Destinations.
        /// </summary>
        public static string RecomendedDestionations {
            get {
                return ResourceManager.GetString("RecomendedDestionations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendations.
        /// </summary>
        public static string Recommendations {
            get {
                return ResourceManager.GetString("Recommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region added successfully.
        /// </summary>
        public static string RegionAddedSuccessfully {
            get {
                return ResourceManager.GetString("RegionAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region was deleted successfully.
        /// </summary>
        public static string RegionDeletedSuccessfully {
            get {
                return ResourceManager.GetString("RegionDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region info was updated successfully.
        /// </summary>
        public static string RegionEditedSuccessfully {
            get {
                return ResourceManager.GetString("RegionEditedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Such region does not exist.
        /// </summary>
        public static string RegionNotExist {
            get {
                return ResourceManager.GetString("RegionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Of The Route.
        /// </summary>
        public static string RegionOfTheRoute {
            get {
                return ResourceManager.GetString("RegionOfTheRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions.
        /// </summary>
        public static string Regions {
            get {
                return ResourceManager.GetString("Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrate.
        /// </summary>
        public static string Registrate {
            get {
                return ResourceManager.GetString("Registrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrtion completed! Confirm your registration via email..
        /// </summary>
        public static string RegistrationCompletedSuccesfully {
            get {
                return ResourceManager.GetString("RegistrationCompletedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration confirmation.
        /// </summary>
        public static string RegistrationConfirmation {
            get {
                return ResourceManager.GetString("RegistrationConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration completed succesfully!.
        /// </summary>
        public static string RegistrationConfirmed {
            get {
                return ResourceManager.GetString("RegistrationConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve just registrated on service ITourist. Registration passed succesfully. Your password In order to confirm your regstration follow this link please : {0}..
        /// </summary>
        public static string RegistrationMessage {
            get {
                return ResourceManager.GetString("RegistrationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string RegistrationTopic {
            get {
                return ResourceManager.GetString("RegistrationTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reidan Abdi.
        /// </summary>
        public static string Reidan {
            get {
                return ResourceManager.GetString("Reidan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove completely.
        /// </summary>
        public static string RemoveCompletely {
            get {
                return ResourceManager.GetString("RemoveCompletely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from the route.
        /// </summary>
        public static string RemovePlaceFromRoute {
            get {
                return ResourceManager.GetString("RemovePlaceFromRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This route is public. If you remove it, it will be removed from your bookmarks and from bookmarks of all other users who have this route in bookmarks. You will not be able to restore it..
        /// </summary>
        public static string RemovePublicNotification {
            get {
                return ResourceManager.GetString("RemovePublicNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove route.
        /// </summary>
        public static string RemoveRoute {
            get {
                return ResourceManager.GetString("RemoveRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder places below in the order you need.
        /// </summary>
        public static string ReorderPlace {
            get {
                return ResourceManager.GetString("ReorderPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Password, please.
        /// </summary>
        public static string RepeatPassword {
            get {
                return ResourceManager.GetString("RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route was created successfully.
        /// </summary>
        public static string RouteCreated {
            get {
                return ResourceManager.GetString("RouteCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route creating.
        /// </summary>
        public static string RouteCreating {
            get {
                return ResourceManager.GetString("RouteCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route is empty.
        /// </summary>
        public static string RouteEmpty {
            get {
                return ResourceManager.GetString("RouteEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string RouteError {
            get {
                return ResourceManager.GetString("RouteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route not found.
        /// </summary>
        public static string RouteNotFound {
            get {
                return ResourceManager.GetString("RouteNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route preview.
        /// </summary>
        public static string RoutePreview {
            get {
                return ResourceManager.GetString("RoutePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My_Route.
        /// </summary>
        public static string RouteRandomName {
            get {
                return ResourceManager.GetString("RouteRandomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routes.
        /// </summary>
        public static string Routes {
            get {
                return ResourceManager.GetString("Routes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route saved.
        /// </summary>
        public static string RouteSaved {
            get {
                return ResourceManager.GetString("RouteSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route was succesfully added to your routes..
        /// </summary>
        public static string RouteWasAdded {
            get {
                return ResourceManager.GetString("RouteWasAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save route.
        /// </summary>
        public static string SaveRoute {
            get {
                return ResourceManager.GetString("SaveRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search country....
        /// </summary>
        public static string SearchCountry {
            get {
                return ResourceManager.GetString("SearchCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search: .
        /// </summary>
        public static string SearchFor {
            get {
                return ResourceManager.GetString("SearchFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing found.
        /// </summary>
        public static string SearchFoundNothing {
            get {
                return ResourceManager.GetString("SearchFoundNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search place....
        /// </summary>
        public static string SearchPlace {
            get {
                return ResourceManager.GetString("SearchPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search region....
        /// </summary>
        public static string SearchRegion {
            get {
                return ResourceManager.GetString("SearchRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results on request &quot;{0}&quot;.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search route....
        /// </summary>
        public static string SearchRoute {
            get {
                return ResourceManager.GetString("SearchRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit route.
        /// </summary>
        public static string SubmitRoute {
            get {
                return ResourceManager.GetString("SubmitRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to that are worth seeing.
        /// </summary>
        public static string ThatAreWorthSeeing {
            get {
                return ResourceManager.GetString("ThatAreWorthSeeing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THERE ARE PLENTY OF PLACES.
        /// </summary>
        public static string ThereArePlentyOfPlaces {
            get {
                return ResourceManager.GetString("ThereArePlentyOfPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to three star of five.
        /// </summary>
        public static string ThreeStarOfFive {
            get {
                return ResourceManager.GetString("ThreeStarOfFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to homepage.
        /// </summary>
        public static string ToHome {
            get {
                return ResourceManager.GetString("ToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  to live a comment.
        /// </summary>
        public static string ToLeaveComment {
            get {
                return ResourceManager.GetString("ToLeaveComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Destinations.
        /// </summary>
        public static string TopDestinations {
            get {
                return ResourceManager.GetString("TopDestinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total distance.
        /// </summary>
        public static string TotalDistance {
            get {
                return ResourceManager.GetString("TotalDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total duration.
        /// </summary>
        public static string TotalDuration {
            get {
                return ResourceManager.GetString("TotalDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel!.
        /// </summary>
        public static string Travel {
            get {
                return ResourceManager.GetString("Travel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need at least two places to create a route.
        /// </summary>
        public static string TwoPlacesNeeded {
            get {
                return ResourceManager.GetString("TwoPlacesNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to two star of five.
        /// </summary>
        public static string TwoStarOfFive {
            get {
                return ResourceManager.GetString("TwoStarOfFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unconirmed Route.
        /// </summary>
        public static string UnconfirmedRoute {
            get {
                return ResourceManager.GetString("UnconfirmedRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can always pass these routes with your mobile iTourist app.
        /// </summary>
        public static string UseMobileAppToPassRoutes {
            get {
                return ResourceManager.GetString("UseMobileAppToPassRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was added successfully.
        /// </summary>
        public static string UserAddedSuccessfully {
            get {
                return ResourceManager.GetString("UserAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with such email already exists.
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was deleted successfully.
        /// </summary>
        public static string UserDeletedSuccessfully {
            get {
                return ResourceManager.GetString("UserDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User info updated successfully.
        /// </summary>
        public static string UserEditedSuccessfully {
            get {
                return ResourceManager.GetString("UserEditedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string UserEmail {
            get {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You loged in successfully.
        /// </summary>
        public static string UserLogedIn {
            get {
                return ResourceManager.GetString("UserLogedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Such user does not exist.
        /// </summary>
        public static string UserNotExists {
            get {
                return ResourceManager.GetString("UserNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View on map.
        /// </summary>
        public static string ViewOnMap {
            get {
                return ResourceManager.GetString("ViewOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View selected places.
        /// </summary>
        public static string ViewSelectedPlaces {
            get {
                return ResourceManager.GetString("ViewSelectedPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vladimir Gritsenko.
        /// </summary>
        public static string Vova {
            get {
                return ResourceManager.GetString("Vova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch my routes.
        /// </summary>
        public static string WatchMyRoutes {
            get {
                return ResourceManager.GetString("WatchMyRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch current  route.
        /// </summary>
        public static string WatchRoute {
            get {
                return ResourceManager.GetString("WatchRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is «iTourist»?.
        /// </summary>
        public static string WhatIsITourist {
            get {
                return ResourceManager.GetString("WhatIsITourist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to where you want to go.
        /// </summary>
        public static string WhereYouWantToGo {
            get {
                return ResourceManager.GetString("WhereYouWantToGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have just added to your route place from region {0}. You can add places to this route from the appropriate region only! .
        /// </summary>
        public static string YoHaveJustAddedToYourRoutePlaceFromRegion {
            get {
                return ResourceManager.GetString("YoHaveJustAddedToYourRoutePlaceFromRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not saved any routes to your bookmarks yet.
        /// </summary>
        public static string YouHaveNoBookmarks {
            get {
                return ResourceManager.GetString("YouHaveNoBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You try to add place from other region to your route..
        /// </summary>
        public static string YouTryToAddPlaceFromOtherRegionToYourRoute {
            get {
                return ResourceManager.GetString("YouTryToAddPlaceFromOtherRegionToYourRoute", resourceCulture);
            }
        }
    }
}
