//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITourist.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckIn
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int CheckPointId { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
    
        public virtual CheckPoint CheckPoint { get; set; }
        public virtual User User { get; set; }
    }
}
