//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITourist.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place
    {
        public Place()
        {
            this.CheckPoints = new HashSet<CheckPoint>();
            this.Comments = new HashSet<Comment>();
            this.LikesToPlaces = new HashSet<LikesToPlace>();
            this.Photos = new HashSet<Photo>();
        }
    
        public int Id { get; set; }
        public int Name { get; set; }
        public short TypeId { get; set; }
        public int Description { get; set; }
        public int RegionId { get; set; }
        public double Rating { get; set; }
        public double X { get; set; }
        public double Y { get; set; }
        public string Image { get; set; }
        public bool Confirmed { get; set; }
    
        public virtual ICollection<CheckPoint> CheckPoints { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<LikesToPlace> LikesToPlaces { get; set; }
        public virtual ICollection<Photo> Photos { get; set; }
        public virtual Region Region { get; set; }
        public virtual Translation Translation { get; set; }
        public virtual Translation Translation1 { get; set; }
    }
}
