//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITourist.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public Route()
        {
            this.Bookmarks = new HashSet<Bookmark>();
            this.CheckPoints = new HashSet<CheckPoint>();
        }
    
        public int Id { get; set; }
        public int Name { get; set; }
        public int Author { get; set; }
        public short Status { get; set; }
        public double Rating { get; set; }
    
        public virtual ICollection<Bookmark> Bookmarks { get; set; }
        public virtual ICollection<CheckPoint> CheckPoints { get; set; }
        public virtual User User { get; set; }
        public virtual Translation Translation { get; set; }
    }
}
