//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITourist.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Translation
    {
        public Translation()
        {
            this.Countries = new HashSet<Country>();
            this.Places = new HashSet<Place>();
            this.Places1 = new HashSet<Place>();
            this.Regions = new HashSet<Region>();
            this.Routes = new HashSet<Route>();
        }
    
        public int Id { get; set; }
        public string En { get; set; }
        public string Ru { get; set; }
    
        public virtual ICollection<Country> Countries { get; set; }
        public virtual ICollection<Place> Places { get; set; }
        public virtual ICollection<Place> Places1 { get; set; }
        public virtual ICollection<Region> Regions { get; set; }
        public virtual ICollection<Route> Routes { get; set; }
    }
}
