//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITourist.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Bookmarks = new HashSet<Bookmark>();
            this.CheckIns = new HashSet<CheckIn>();
            this.Comments = new HashSet<Comment>();
            this.LikesToPlaces = new HashSet<LikesToPlace>();
            this.Routes = new HashSet<Route>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string FacebookLogin { get; set; }
        public string GoogleLogin { get; set; }
        public string VkLogin { get; set; }
        public string Image { get; set; }
        public int Experience { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public short Status { get; set; }
        public System.DateTime RegistrationDate { get; set; }
    
        public virtual ICollection<Bookmark> Bookmarks { get; set; }
        public virtual ICollection<CheckIn> CheckIns { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<LikesToPlace> LikesToPlaces { get; set; }
        public virtual ICollection<Route> Routes { get; set; }
    }
}
